require: 
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - './bin/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*'
