require: 
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'app/views/**/*.html.erb'
    - 'vendor/**/*'
    - './bin/**/*'
    - 'db/migrate/**/*'
    - 'db/schema'
    - 'docs/**/*'

Style/Documentation:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Max: 12

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
