name: Rspec Tests

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env:
      POSTGRES_DB: rails_test
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

env:
  RAILS_ENV: test
  DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@cacc9f1c0b3f4eb8a16a6bb0ed10897b43b9de49 # v1.176.0
      with:
        bundler-cache: true
    - run: sudo systemctl start postgresql.service
      shell: bash

    - run: sudo -u postgres createuser --createdb --superuser ${USER}
      shell: bash

    - run: createdb ${USER}
      shell: bash
    - name: Set up database schema
      shell: bash
      run: bin/rails db:schema:load
    - name: Run tests
      shell: bash
      run: bin/rspec