name: Rspec Tests
runs-on: ubuntu-latest
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v4
      with:
        node-version: ">=23.0.0"
    - name: Set up database schema
      shell: bash
      run: bin/rails db:schema:load
    - name: Install Yarn
      shell: bash
      run: npm install -g yarn
    - name: Set up assets
      shell: bash
      run: bin/rails assets:precompile
    - name: Run tests
      shell: bash
      run: bin/rspec
