name: Typescript Linting

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ">=23.0.0"
    - name: Install modules
      shell: bash
      run: yarn
    - name: Lint Typescript files
      shell: bash
      run: yarn lint:js
