name: Cypress Tests
runs-on: ubuntu-latest
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        build: yarn run build
        start: yarn start