/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/Private_Jet_C.gltf 
*/

import { useGLTF } from '@react-three/drei';
import { Props } from '@react-three/fiber';
import React from 'react';
import * as THREE from 'three';
import { nullEventHandlers } from '../utils/nullEventHandlers';

export function PrivateJet({id, ...props}:Props) {
  const { nodes, materials } = useGLTF('/Private_Jet_C.gltf')
  const ambientColor = new THREE.Color(0x666666)
  const meshNodes: Record<string, THREE.Mesh> = nodes as Record<string, THREE.Mesh>

  return (
    <>
      <rectAreaLight color={0xffffff} intensity={1} width={10} height={10} position={[0, 2, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <ambientLight color={ambientColor} />
      <group {...props} {...nullEventHandlers} dispose={null} >
        <mesh geometry={meshNodes.kitchen_wall_01_1001.geometry} material={materials.mat_kitchen_wall_01_1001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.kitchen_wall_02_1001.geometry} material={materials.mat_kitchen_wall_01_1001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.kitchen_wall_03_1001.geometry} material={materials.mat_kitchen_wall_01_1001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.kitchen_wall_04_1001.geometry} material={materials.mat_kitchen_wall_01_1001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.kitchen_wall_05_1001.geometry} material={materials.mat_Glass} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.kitchen_wall_06_1001.geometry} material={materials.mat_Glass} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.Flooring_1002.geometry} material={materials.mat_Flooring_1002} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.fuselage_walls_L_1003.geometry} material={materials.mat_fuselage_walls_1003} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.fuselage_walls_R_1003.geometry} material={materials.mat_fuselage_walls_1003} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01} />
        <mesh geometry={meshNodes.Portholes_R_1003.geometry} material={materials.mat_fuselage_walls_1003} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.Portholes_L_1003.geometry} material={materials.mat_fuselage_walls_1003} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.Ceiling_1003.geometry} material={materials.mat_fuselage_walls_1003} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.Wall_panel_R_1004.geometry} material={materials.mat_Wall_panel_R_1004} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01} />
        <mesh geometry={meshNodes.Wall_panel_L_1004.geometry} material={materials.mat_Wall_panel_R_1004} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.table_01_1004.geometry} material={materials.mat_Wall_panel_R_1004} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01} />
        <mesh geometry={meshNodes.table_02_1004.geometry} material={materials.mat_Wall_panel_R_1004} position={[2.453, 0, -1.492]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01} />
        <mesh geometry={meshNodes.table_03_1004.geometry} material={materials.mat_Wall_panel_R_1004} position={[0, 0, -1.492]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01} />
        <mesh geometry={meshNodes.Partial_fuselage_1005.geometry} material={materials.mat_Plane_1005} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.Plane_1005.geometry} material={materials.mat_Plane_1005} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.armchair_1006_01.geometry} material={materials.mat_armchair_1006} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01} />
        <mesh geometry={meshNodes.armchair_1006_02.geometry} material={materials.mat_armchair_1006} position={[2.453, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01} />
        <mesh geometry={meshNodes.armchair_1006_03.geometry} material={materials.mat_armchair_1006} position={[2.453, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01} />
        <mesh geometry={meshNodes.armchair_1006_04.geometry} material={materials.mat_armchair_1006} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.armchair_1006_05.geometry} material={materials.mat_armchair_1006} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.armchair_1006_06.geometry} material={materials.mat_armchair_1006} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-0.01} />
        <mesh geometry={meshNodes.sofa_1007.geometry} material={materials.mat_sofa_1007} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={meshNodes.Glass_1008.geometry} material={materials.mat_Glass} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </>
  )
}

useGLTF.preload('/Private_Jet_C.gltf')
