name: Brakeman Security Check
runs-on: ubuntu-latest
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Brakeman run
      uses: artplan1/brakeman-action@v1.2.1
      with:
        flags: "--color"