name: Jest Tests
runs-on: ubuntu-latest
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with: 
        node-version: '>=22.0.0'
    - name: Install Yarn
      shell: bash
      run: npm install -g yarn
    - name: Install modules
      shell: bash
      run: yarn
    - name: Run tests
      shell: bash
      run: yarn test